Reprise globale du package

diff --git a/scripts/backup b/scripts/backup
--- a/scripts/backup
+++ b/scripts/backup
@@ -1,39 +1,66 @@
 #!/bin/bash
 
-# Récupère les infos de l'application.
-app=$YNH_APP_INSTANCE_NAME
+#=================================================
+# GENERIC STARTING
+#=================================================
+# MANAGE FAILURE OF THE SCRIPT
+#=================================================
 
-# Source app helpers
+# Exit on command errors and treat unset variables as an error
+set -eu
+
+#=================================================
+# IMPORT GENERIC HELPERS
+#=================================================
+
+if [ ! -e .fonctions ]; then
+	# Rapatrie le fichier de fonctions si il n'est pas dans le dossier courant
+	sudo cp ../settings/scripts/.fonctions ./.fonctions
+	sudo chmod a+rx .fonctions
+fi
+source .fonctions
 source /usr/share/yunohost/helpers
+
+#=================================================
+# LOAD SETTINGS
+#=================================================
+
+app=$YNH_APP_INSTANCE_NAME
 
 final_path=$(ynh_app_setting_get $app final_path)
 domain=$(ynh_app_setting_get $app domain)
-codename=$(ynh_app_setting_get $app codename)
 
-# The parameter $1 is the backup directory location
-# which will be compressed afterward
-backup_dir=$1/apps/$app
-sudo mkdir -p "$backup_dir"
+#=================================================
+# STANDARD BACKUP STEPS
+#=================================================
+# BACKUP OF THE MAIN DIR OF THE APP
+#=================================================
 
-# Backup sources & data
-sudo cp -a $final_path/. $backup_dir/sources
+CHECK_SIZE "$final_path"
+ynh_backup "$final_path" "sources"
 
-# Copy Nginx and YunoHost parameters to make the script "standalone"
-sudo cp -a /etc/yunohost/apps/$app/. $backup_dir/yunohost
-sudo cp -a /etc/nginx/conf.d/$domain.d/$app.conf $backup_dir/nginx.conf
+#=================================================
+# BACKUP OF THE NGINX CONFIGURATION
+#=================================================
 
-if [ "$codename" = "wheezy" ]
-then
-	# Copie des fichiers du script init
-	sudo cp -a /etc/init.d/lutim $backup_dir/init.d_lutim
-	sudo cp -a /etc/default/lutim $backup_dir/default_lutim
-else
-	# Copie des fichiers du script systemd
-	sudo cp -a /etc/systemd/system/lutim.service $backup_dir/
-fi
+ynh_backup "/etc/nginx/conf.d/$domain.d/$app.conf" "nginx.conf"
 
-# Copie du fichier du cron
-sudo cp -a /etc/cron.d/$app $backup_dir/cron_$app
+#=================================================
+# SPECIFIC BACKUP
+#=================================================
+# BACKUP LOGROTATE
+#=================================================
 
-# Copie la configuration de logrotate
-sudo cp -a /etc/logrotate.d/$app $backup_dir/logrotate
+ynh_backup "/etc/logrotate.d/$app" "logrotate"
+
+#=================================================
+# BACKUP SYSTEMD
+#=================================================
+
+ynh_backup "/etc/systemd/system/$app.service" "systemd"
+
+#=================================================
+# BACKUP OF THE CRON FILE
+#=================================================
+
+ynh_backup "/etc/cron.d/$app" "cron"
diff --git a/scripts/install b/scripts/install
--- a/scripts/install
+++ b/scripts/install
@@ -1,164 +1,196 @@
 #!/bin/bash
 
-source .fonctions	# Charge les fonctions génériques habituellement utilisées dans le script
+#=================================================
+# GENERIC STARTING
+#=================================================
+# IMPORT GENERIC HELPERS
+#=================================================
 
-CLEAN_SETUP () {
-# Nettoyage des résidus d'installation non pris en charge par le script remove.
-# Pas de nettoyage supplémentaire nécessaire ici...
-	echo ""
-}
-TRAP_ON	# Active trap pour arrêter le script si une erreur est détectée.
+source .fonctions
+source /usr/share/yunohost/helpers
 
-# Retrieve arguments
+#=================================================
+# MANAGE FAILURE OF THE SCRIPT
+#=================================================
+
+ynh_abort_if_errors	# Active trap pour arrêter le script si une erreur est détectée.
+
+#=================================================
+# RETRIEVE ARGUMENTS FROM THE MANIFEST
+#=================================================
+
 domain=$YNH_APP_ARG_DOMAIN
-path=$YNH_APP_ARG_PATH
+path_url=$YNH_APP_ARG_PATH
 admin=$YNH_APP_ARG_ADMIN
 is_public=$YNH_APP_ARG_IS_PUBLIC
 always_encrypt=$YNH_APP_ARG_ALWAYS_ENCRYPT
 
 app=$YNH_APP_INSTANCE_NAME
 
-# Source app helpers
-source /usr/share/yunohost/helpers
-
-script_dir=$PWD
-
-# Vérifie que les variables ne sont pas vides.
-CHECK_VAR "$app" "app name not set"
-CHECK_VAR "$script_dir" "script_dir not set"
-
+#=================================================
+# CHECK IF THE APP CAN BE INSTALLED WITH THIS ARGS
+#=================================================
 
 CHECK_USER "$admin"	# Vérifie la validité de l'user admin
-
-CHECK_PATH	# Vérifie et corrige la syntaxe du path.
+path_url=$(ynh_normalize_url_path $path_url)	# Vérifie et corrige la syntaxe du path.
 CHECK_DOMAINPATH	# Vérifie la disponibilité du path et du domaine.
-
 CHECK_FINALPATH	# Vérifie que le dossier de destination n'est pas déjà utilisé.
 
-# Modifie le domaine pour qu'il passe dans une regex
-domain_regex=$(echo "$domain" | sed 's@-@.@g')
-CHECK_VAR "$domain_regex" "domain_regex empty"
+#=================================================
+# STORE SETTINGS FROM MANIFEST
+#=================================================
 
-FIND_PORT 8095	# Cherche un port libre.
-
-# Enregistre les infos dans la config YunoHost
 ynh_app_setting_set $app admin $admin
 ynh_app_setting_set $app domain $domain
 ynh_app_setting_set $app is_public $is_public
-ynh_app_setting_set $app port $port
 ynh_app_setting_set $app always_encrypt $always_encrypt
 
+#=================================================
+# STANDARD MODIFICATIONS
+#=================================================
+# FIND AND OPEN A PORT
+#=================================================
 
-# Créer le repertoire de destination et stocke son emplacement.
-sudo mkdir "$final_path"
+port=$(ynh_find_port 8095)	# Cherche un port libre.
+# Ouvre le port dans le firewall
+ALL_QUIET sudo yunohost firewall allow --no-upnp TCP $port
+ynh_app_setting_set $app port $port
+
+#=================================================
+# DOWNLOAD, CHECK AND UNPACK SOURCE
+#=================================================
+
 ynh_app_setting_set $app final_path $final_path
+SETUP_SOURCE	# Télécharge la source, décompresse et copie dans $final_path
 
-SETUP_SOURCE "lutim.tar.gz"	# Télécharge la source, décompresse et copie dans $final_path
+#=================================================
+# INSTALL DEPENDENCIES
+#=================================================
+
+ynh_install_app_dependencies carton perlmagick
+
+#=================================================
+# NGINX CONFIGURATION
+#=================================================
 
 # Copie le fichier de config nginx
 sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf
+# Change variables in nginx configuration
+sudo sed -i "s@__PATH__@$path_url@g" /etc/nginx/conf.d/$domain.d/$app.conf
+sudo sed -i "s@__PORT__@$port@g" /etc/nginx/conf.d/$domain.d/$app.conf
 
+#=================================================
+# CREATE DEDICATED USER
+#=================================================
 
-# Installation de perlmagick, interface perl pour imagemagick et de carton, gestionnaire de dépendances perl
-sudo apt-get update
-sudo apt-get install carton perlmagick -qy
+ynh_system_user_create $app	# Créer un utilisateur système dédié à l'app
+
+#=================================================
+# SPECIFIC SETUP
+#=================================================
+# SETUP LUTIM
+#=================================================
 
 ## Copie et configuration du fichier de conf.
 sudo cp ../conf/lutim.conf.template "$final_path/lutim.conf"
 sudo sed -i "s@__DOMAIN__@$domain@g" "$final_path/lutim.conf"
-sudo sed -i "s@__PATH__@$path@g" "$final_path/lutim.conf"
+sudo sed -i "s@__PATH__@$path_url@g" "$final_path/lutim.conf"
 sudo sed -i "s@__PORT__@$port@g" "$final_path/lutim.conf"
-if [ "$always_encrypt" = "No" ]; then
-	always_encrypt=0
-else
-	always_encrypt=1
-fi
 sudo sed -i "s@__ENCRYPT__@$always_encrypt@g" "$final_path/lutim.conf"
-secret=$(dd if=/dev/urandom bs=1 count=200 2> /dev/null | tr -c -d 'A-Za-z0-9' | sed -n 's/\(.\{24\}\).*/\1/p')
-CHECK_VAR "$secret" "secret empty"
+secret=$(ynh_string_random)
 sudo sed -i "s@__SECRET__@$secret@g" "$final_path/lutim.conf"
 STORE_MD5_CONFIG "lutim.conf" "$final_path/lutim.conf"	# Enregistre la somme de contrôle du fichier de config
 
+#=================================================
+# SETUP SYSTEMD
+#=================================================
 
-codename=$(lsb_release -a 2>/dev/null | grep Codename | cut -f 2)
-CHECK_VAR "$codename" "codename empty"
-ynh_app_setting_set $app codename $codename
-if [ "$codename" = "wheezy" ]
-then	# On utilise le script init pour wheezy.
-	# Mise en place du script init
-	sudo cp ../conf/lutim.init /etc/init.d/lutim
-	sudo cp ../conf/lutim.default /etc/default/lutim
-	sudo chmod +x /etc/init.d/lutim
-	sudo chown root: /etc/init.d/lutim /etc/default/lutim
-	sudo sed -i "s@__FINALPATH__@$final_path/@g" /etc/default/lutim
-	## Démarrage auto du service
-	sudo update-rc.d lutim defaults
-else	# Et le script systemd à partir de jessie
-	# Mise en place du script systemd
-	sudo cp ../conf/lutim.service /etc/systemd/system/lutim.service
-	sudo chown root: /etc/systemd/system/lutim.service
-	sudo sed -i "s@__FINALPATH__@$final_path/@g" /etc/systemd/system/lutim.service
-	## Démarrage auto du service
-	sudo systemctl enable lutim.service
-fi
+sudo cp ../conf/lutim.service /etc/systemd/system/$app.service
+sudo chown root: /etc/systemd/system/$app.service
+sudo sed -i "s@__FINALPATH__@$final_path/@g" /etc/systemd/system/$app.service
+sudo sed -i "s@__APP__@$app@g" /etc/systemd/system/$app.service
+## Démarrage auto du service
+sudo systemctl enable $app
 
-## Mise en place des crons
+#=================================================
+# SETUP CRON
+#=================================================
+
 sudo cp ../conf/cron_lutim /etc/cron.d/$app
 sudo sed -i "s@__FINALPATH__@$final_path/@g" /etc/cron.d/$app
 sudo chmod +x $final_path/script/lutim
 
-# Configuration de logrotate
-sed -i "s@__FINALPATH__@$final_path@g" ../conf/logrotate
-sudo cp ../conf/logrotate /etc/logrotate.d/$app
+#=================================================
+# INSTALL LUTIM WITH CARTON
+#=================================================
 
-# Installation de lutim via carton
 sudo mkdir -p /var/log/$app/
-cd $final_path
+pushd $final_path	# cd avec une stack pour revenir en arrière
 sudo carton install 2>&1 | sudo tee -a "/var/log/$app/setup_carton.log"
+popd	# Revient au dossier courant avant pushd
 
 # Configure le path du dossier perl en fonction de l'architecture système
 arch_dir=$(ls -1 $final_path/local/lib/perl5/ | grep linux-gnu)
 if [ "$?" -ne 0 ]
 then
-    echo "Impossible de trouver le dossier relatif à l'architecture système." | sudo tee -a "/var/log/$app/setup_carton.log"
-	false
+	ynh_die "Impossible de trouver le dossier relatif à l'architecture système."
 fi
-CHECK_VAR "$arch_dir" "arch_dir empty"
 sudo sed -i "s@__ARCHDIR__@$arch_dir@g" "$final_path/script/lutim"
 
-# Change variables in nginx configuration
-sudo sed -i "s@__PATH__@$path@g" /etc/nginx/conf.d/$domain.d/$app.conf
-sudo sed -i "s@__PORT__@$port@g" /etc/nginx/conf.d/$domain.d/$app.conf
-
-# Make app public or private
-ynh_app_setting_set $app skipped_uris "/"
-if [ "$is_public" = "No" ];
-then	# Si l'app est privée, seul le visionnage des images reste public
-	if [ "$path" == "/" ]; then
-	    path=""	# Si path correspond à la racine, supprime le / pour éviter une erreur de la regex.
-	fi
-	ynh_app_setting_set $app protected_regex "$domain_regex$path/stats$","$domain_regex$path/manifest.webapp$","$domain_regex$path/$","$domain_regex$path/d/.*$","$domain_regex$path/m/.*$"
-fi
+#=================================================
+# SETUP LOG FILE
+#=================================================
 
 # Making log symbolic link to /var/log
-sudo touch /var/log/$app/production.log 
-sudo chown www-data: /var/log/$app/production.log
+sudo touch /var/log/$app/production.log
+sudo chown $app: -R /var/log/$app
 sudo ln -s /var/log/$app/production.log "$final_path/log/production.log"
 
-# Configure les droits d'accès au fichiers
-sudo chown -R www-data: $final_path
+#=================================================
+# SECURING FILES AND DIRECTORIES
+#=================================================
 
-# Start lutim
-sudo service lutim start
+sudo chown -R $app: $final_path
+
+#=================================================
+# START LUTIM
+#=================================================
+
+sudo systemctl start lutim
 # Set right permissions on new files created at first start
-sudo chown -R www-data: "$final_path"
+sudo chown -R $app: $final_path
 
+#=================================================
+# GENERIC FINALISATION
+#=================================================
+# SETUP LOGROTATE
+#=================================================
 
-# Add lutim as a service
+ynh_use_logrotate
+
+#=================================================
+# ENABLE SERVICE IN ADMIN PANEL
+#=================================================
+
 sudo yunohost service add lutim -l $final_path/log/production.log
 
+#=================================================
+# SETUP SSOWAT
+#=================================================
 
-# Recharge la configuration Nginx
-sudo service nginx reload
-# Régénère la configuration de SSOwat
-sudo yunohost app ssowatconf
+ynh_app_setting_set $app skipped_uris "/"
+if [ $is_public -eq 0 ]
+then	# Si l'app est privée, seul le visionnage des images reste public
+	if [ "$path_url" == "/" ]; then
+	    path_url=""	# Si path correspond à la racine, supprime le / pour éviter une erreur de la regex.
+	fi
+	# Modifie le domaine pour qu'il passe dans une regex
+	domain_regex=$(echo "$domain" | sed 's@-@.@g')
+	ynh_app_setting_set $app protected_regex "$domain_regex$path_url/stats$","$domain_regex$path_url/manifest.webapp$","$domain_regex$path_url/$","$domain_regex$path_url/d/.*$","$domain_regex$path_url/m/.*$"
+fi
+
+#=================================================
+# RELOAD NGINX
+#=================================================
+
+sudo systemctl reload nginx
diff --git a/scripts/restore b/scripts/restore
--- a/scripts/restore
+++ b/scripts/restore
@@ -1,58 +1,123 @@
 #!/bin/bash
 
-# Récupère les infos de l'application.
-app=$YNH_APP_INSTANCE_NAME
+#=================================================
+# GENERIC STARTING
+#=================================================
+# MANAGE FAILURE OF THE SCRIPT
+#=================================================
 
-# Source app helpers
+# Exit on command errors and treat unset variables as an error
+set -eu
+
+#=================================================
+# IMPORT GENERIC HELPERS
+#=================================================
+
+if [ ! -e .fonctions ]; then
+	# Rapatrie le fichier de fonctions si il n'est pas dans le dossier courant
+	sudo cp ../settings/scripts/.fonctions ./.fonctions
+	sudo chmod a+rx .fonctions
+fi
+source .fonctions
 source /usr/share/yunohost/helpers
+
+#=================================================
+# LOAD SETTINGS
+#=================================================
+
+app=$YNH_APP_INSTANCE_NAME
 
 final_path=$(ynh_app_setting_get $app final_path)
 domain=$(ynh_app_setting_get $app domain)
-codename=$(ynh_app_setting_get $app codename)
+path_url=$(ynh_app_setting_get $app path)
 
-# The parameter $1 is the uncompressed restore directory location
-backup_dir=$1/apps/$app
+#=================================================
+# CHECK IF THE APP CAN BE RESTORED
+#=================================================
 
-# Restore sources & data
-sudo cp -a $backup_dir/sources/. $final_path
+sudo yunohost app checkurl "${domain}${path_url}" -a "$app" \
+	|| ynh_die "Path not available: ${domain}${path_url}"
+test ! -d $final_path \
+	|| ynh_die "There is already a directory: $final_path "
 
-# Restore Nginx and YunoHost parameters
-sudo cp -a $backup_dir/yunohost/. /etc/yunohost/apps/$app
-sudo cp -a $backup_dir/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf
+#=================================================
+# STANDARD RESTORE STEPS
+#=================================================
+# RESTORE OF THE NGINX CONFIGURATION
+#=================================================
 
-
-# Installation de perlmagick, interface perl pour imagemagick et de carton, gestionnaire de dépendances perl
-sudo apt-get update
-sudo apt-get install carton perlmagick -qy
-
-
-if [ "$codename" = "wheezy" ]
-then
-	# Restauration des fichiers du script init
-	sudo cp -a $backup_dir/init.d_lutim /etc/init.d/lutim
-	sudo cp -a $backup_dir/default_lutim /etc/default/lutim
-	## Démarrage auto du service
-	sudo update-rc.d lutim defaults
-else
-	# Restauration des fichiers du script systemd
-	sudo cp -a $backup_dir/lutim.service /etc/systemd/system/lutim.service
-	## Démarrage auto du service
-	sudo systemctl enable lutim.service
+conf=/etc/nginx/conf.d/$domain.d/$app.conf
+if [ -f $conf ]; then
+	ynh_die "There is already a nginx conf file at this path: $conf "
 fi
+sudo cp -a ./nginx.conf $conf
 
+#=================================================
+# RESTORE OF THE MAIN DIR OF THE APP
+#=================================================
 
-# Restauration du fichier du cron
-sudo cp -a $backup_dir/cron_$app /etc/cron.d/$app
+sudo cp -a ./sources/. $final_path
+
+#=================================================
+# RECREATE OF THE DEDICATED USER
+#=================================================
+
+ynh_system_user_create $app	# Recreate the dedicated user, if not exist
+
+#=================================================
+# RESTORE USER RIGHTS
+#=================================================
+
+# Les fichiers appartiennent à root
+sudo chown -R $app: $final_path
+
+#=================================================
+# SPECIFIC RESTORE
+#=================================================
+# REINSTALL DEPENDENCIES
+#=================================================
+
+ynh_install_app_dependencies carton perlmagick
+
+#=================================================
+# ENABLE SERVICE IN ADMIN PANEL
+#=================================================
+
+sudo yunohost service add $app --log "/var/log/$app/APP.log"
+
+#=================================================
+# RESTORE SYSTEMD
+#=================================================
+
+sudo cp -a ./systemd /etc/systemd/system/$app.service
+## Démarrage auto du service
+sudo systemctl enable $app.service
+
+#=================================================
+# RESTORE OF THE CRON FILE
+#=================================================
+
+sudo cp -a "cron" "/etc/cron.d/$app"
+
+#=================================================
+# SETUP LOG FILE
+#=================================================
 
 # Making log symbolic link to /var/log
 sudo mkdir -p /var/log/$app/
-sudo touch /var/log/$app/production.log 
-sudo chown www-data: /var/log/$app/production.log
-# Restaure la configuration de logrotate
-sudo cp -a $backup_dir/logrotate /etc/logrotate.d/$app
+sudo touch /var/log/$app/production.log
+sudo chown $app: -R /var/log/$app
 
-# Restart webserver
-sudo service nginx reload
+#=================================================
+# START LUTIM
+#=================================================
 
-# Start lutim
-sudo service lutim start
+sudo systemctl start lutim
+
+#=================================================
+# GENERIC FINALISATION
+#=================================================
+# RELOAD NGINX
+#=================================================
+
+sudo systemctl reload nginx
diff --git a/scripts/upgrade b/scripts/upgrade
--- a/scripts/upgrade
+++ b/scripts/upgrade
@@ -1,106 +1,170 @@
 #!/bin/bash
 
-source .fonctions	# Charge les fonctions génériques habituellement utilisées dans le script
+#=================================================
+# GENERIC STARTING
+#=================================================
+# IMPORT GENERIC HELPERS
+#=================================================
 
-# Récupère les infos de l'application.
-app=$YNH_APP_INSTANCE_NAME
-
-# Source app helpers
+source .fonctions
 source /usr/share/yunohost/helpers
 
+#=================================================
+# LOAD SETTINGS
+#=================================================
+
+app=$YNH_APP_INSTANCE_NAME
+
 domain=$(ynh_app_setting_get $app domain)
-path=$(ynh_app_setting_get $app path)
+path_url=$(ynh_app_setting_get $app path)
 is_public=$(ynh_app_setting_get $app is_public)
 port=$(ynh_app_setting_get $app port)
 always_encrypt=$(ynh_app_setting_get $app always_encrypt)
 final_path=$(ynh_app_setting_get $app final_path)
+
+#=================================================
+# FIX OLD THINGS
+#=================================================
+
+if [ "$is_public" = "Yes" ]; then
+	ynh_app_setting_set $app is_public 1	# Fixe is_public en booléen
+	is_public=1
+elif [ "$is_public" = "No" ]; then
+	ynh_app_setting_set $app is_public 0
+	is_public=0
+fi
 
 if [ "${#final_path}" -eq 0 ]
 then	# Si final_path n'est pas renseigné dans la config yunohost, cas d'ancien script, code final_path en dur
 	final_path=/var/www/$app
 fi
 
+if [ "$always_encrypt" = "Yes" ]; then
+	ynh_app_setting_set $app always_encrypt 1	# Fixe always_encrypt en booléen
+	always_encrypt=1
+elif [ "$always_encrypt" = "No" ]; then
+	ynh_app_setting_set $app always_encrypt 0
+	always_encrypt=0
+fi
 
-CHECK_PATH	# Vérifie et corrige la syntaxe du path.
-# Modifie le domaine pour qu'il passe dans une regex
-domain_regex=$(echo "$domain" | sed 's@-@.@g')
+#=================================================
+# BACKUP BEFORE UPGRADE THEN ACTIVE TRAP
+#=================================================
 
-SETUP_SOURCE "lutim.tar.gz"	# Télécharge la source, décompresse et copie dans $final_path
+BACKUP_BEFORE_UPGRADE	# Backup the current version of the app
+ynh_clean_setup () {
+	BACKUP_FAIL_UPGRADE	# restore it if the upgrade fails
+}
+ynh_abort_if_errors	# Active trap pour arrêter le script si une erreur est détectée.
+
+#=================================================
+# CHECK THE PATH
+#=================================================
+
+path_url=$(ynh_normalize_url_path $path_url)	# Vérifie et corrige la syntaxe du path.
+
+#=================================================
+# STANDARD UPGRADE STEPS
+#=================================================
+# DOWNLOAD, CHECK AND UNPACK SOURCE
+#=================================================
+
+SETUP_SOURCE	# Télécharge la source, décompresse et copie dans $final_path
+
+#=================================================
+# NGINX CONFIGURATION
+#=================================================
 
 # Et copie le fichier de config nginx
 sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf
-
 # Change variables in nginx configuration
-sudo sed -i "s@__PATH__@$path@g" /etc/nginx/conf.d/$domain.d/$app.conf
+sudo sed -i "s@__PATH__@$path_url@g" /etc/nginx/conf.d/$domain.d/$app.conf
 sudo sed -i "s@__PORT__@$port@g" /etc/nginx/conf.d/$domain.d/$app.conf
+
+#=================================================
+# CREATE DEDICATED USER
+#=================================================
+
+ynh_system_user_create $app	# Create the dedicated user, if not exist
+
+#=================================================
+# SPECIFIC UPGRADE
+#=================================================
+# SETUP LUTIM
+#=================================================
 
 ## Copie et configuration du fichier de conf.
 CHECK_MD5_CONFIG "lutim.conf" "$final_path/lutim.conf"	# Créé un backup du fichier de config si il a été modifié.
 sudo cp ../conf/lutim.conf.template "$final_path/lutim.conf"
 sudo sed -i "s@__DOMAIN__@$domain@g" "$final_path/lutim.conf"
-sudo sed -i "s@__PATH__@$path@g" "$final_path/lutim.conf"
+sudo sed -i "s@__PATH__@$path_url@g" "$final_path/lutim.conf"
 sudo sed -i "s@__PORT__@$port@g" "$final_path/lutim.conf"
-if [ "always_encrypt" = "No" ]; then
-	always_encrypt=0
-else
-	always_encrypt=1
-fi
 sudo sed -i "s@__ENCRYPT__@$always_encrypt@g" "$final_path/lutim.conf"
 STORE_MD5_CONFIG "lutim.conf" "$final_path/lutim.conf"	# Réenregistre la somme de contrôle du fichier de config
 
-codename=$(lsb_release -a 2>/dev/null | grep Codename | cut -f 2)
-ynh_app_setting_set $app codename $codename
-if [ "$codename" = "wheezy" ]
-then	# On utilise le script init pour wheezy.
-	# Mise en place du script init
-	sudo cp ../conf/lutim.init /etc/init.d/lutim
-	sudo cp ../conf/lutim.default /etc/default/lutim
-	sudo chmod +x /etc/init.d/lutim
-	sudo chown root: /etc/init.d/lutim /etc/default/lutim
-	sudo sed -i "s@__FINALPATH__@$final_path/@g" /etc/default/lutim
-	## Démarrage auto du service
-	sudo update-rc.d lutim defaults
-else	# Et le script systemd à partir de jessie
-	if [ -e /etc/init.d/lutim ]
-	then	# Supprime le script init.d si il existe.
-		sudo rm -f /etc/default/lutim
-		sudo rm -f /etc/init.d/lutim
-		sudo update-rc.d -f lutim remove
-	fi
-	# Mise en place du script systemd
-	sudo cp ../conf/lutim.service /etc/systemd/system/lutim.service
-	sudo chown root:root /etc/systemd/system/lutim.service
-	sudo sed -i "s@__FINALPATH__@$final_path/@g" /etc/systemd/system/lutim.service
-	## Démarrage auto du service
-	sudo systemctl enable lutim.service
-fi
+#=================================================
+# SETUP SYSTEMD
+#=================================================
 
-## Mise en place des crons
+# Mise en place du script systemd
+sudo systemctl stop $app
+sudo cp ../conf/lutim.service /etc/systemd/system/$app.service
+sudo chown root: /etc/systemd/system/$app.service
+sudo sed -i "s@__FINALPATH__@$final_path/@g" /etc/systemd/system/$app.service
+sudo sed -i "s@__APP__@$app@g" /etc/systemd/system/$app.service
+## Démarrage auto du service
+sudo systemctl enable $app
+
+#=================================================
+# SETUP CRON
+#=================================================
+
 sudo cp ../conf/cron_lutim /etc/cron.d/$app
 sudo sed -i "s@__FINALPATH__@$final_path/@g" /etc/cron.d/$app
 
-# Configuration de logrotate
-sed -i "s@__FINALPATH__@$final_path@g" ../conf/logrotate
-sudo cp ../conf/logrotate /etc/logrotate.d/$app
+#=================================================
+# UPDATE LUTIM WITH CARTON
+#=================================================
 
-# Mise à jour de lutim via carton
-cd $final_path
+pushd $final_path	# cd avec une stack pour revenir en arrière
 sudo carton install 2>&1 | sudo tee -a "/var/log/$app/setup_carton.log"
+popd	# Revient au dossier courant avant pushd
 
-# Make app public or private
+#=================================================
+# SECURING FILES AND DIRECTORIES
+#=================================================
+
+sudo chown -R $app: $final_path
+
+#=================================================
+# RESTART LUTIM
+#=================================================
+
+sudo systemctl restart lutim
+
+#=================================================
+# GENERIC FINALISATION
+#=================================================
+# SETUP LOGROTATE
+#=================================================
+
+ynh_use_logrotate
+sudo chown $app: -R /var/log/$app
+
+#=================================================
+# SETUP SSOWAT
+#=================================================
+
 ynh_app_setting_set $app skipped_uris "/"
-if [ "$is_public" = "No" ];
+if [ $is_public -eq 0 ]
 then	# Si l'app est privée, seul le visionnage des images reste public
-	ynh_app_setting_set $app protected_regex "$domain_regex$path/stats$","$domain_regex$path/manifest.webapp$","$domain_regex$path/$","$domain_regex$path/d/.*$","$domain_regex$path/m/.*$"
+	# Modifie le domaine pour qu'il passe dans une regex
+	domain_regex=$(echo "$domain" | sed 's@-@.@g')
+	ynh_app_setting_set $app protected_regex "$domain_regex$path_url/stats$","$domain_regex$path_url/manifest.webapp$","$domain_regex$path_url/$","$domain_regex$path_url/d/.*$","$domain_regex$path_url/m/.*$"
 fi
 
-# Configure les droits d'accès au fichiers
-sudo chown -R www-data: $final_path
-# Restart lutim
-sudo service lutim restart
+#=================================================
+# RELOAD NGINX
+#=================================================
 
-
-# Recharge la configuration Nginx
-sudo service nginx reload
-# Régénère la configuration de SSOwat
-sudo yunohost app ssowatconf
+sudo systemctl reload nginx
